name: taskiflow
description: A modern task management app with JWT authentication.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  http: ^1.2.1

  # State Management
  provider: ^6.1.2

  # Secure Token Storage
  flutter_secure_storage: ^9.2.2

  # Shimmer loading effect
  shimmer: ^3.0.0

  # Modern fonts
  google_fonts: ^6.2.1

  # Spacing utility
  gap: ^3.0.1

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
